blog/urls.py
from django.urls import path
from .views import PostList, PostListByTag, PostDetail
from .views import PostYearArchiveView
from .views import PostMonthArchiveView
from .views import PostWeekArchiveView
from .views import PostDayArchiveView
from .views import PostTodayArchiveView
from .views import CommentCreate, CommentReply, ThanksTemplateView

app_name = 'blog'
urlpatterns = [
    # post CBVs
    path('list/', PostList.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>/', PostListByTag.as_view(), name='post_list_by_tag'),
    path('detail/<int:pk>/', PostDetail.as_view(), name='post_detail'),

    path('<int:year>/',
         PostYearArchiveView.as_view(),
         name="post_year_archive"),
    # Example: /2012/08/
    path('<int:year>/<int:month>/',
         PostMonthArchiveView.as_view(month_format='%m'),
         name="archive_month_numeric"),
    # Example: /2012/aug/
    path('<int:year>/<str:month>/',
         PostMonthArchiveView.as_view(),
         name="archive_month"),
    # Example: /2012/week/23/
    path('<int:year>/week/<int:week>/',
         PostWeekArchiveView.as_view(),
         name="archive_week"),
    # Example: /2012/nov/10/
    path('<int:year>/<str:month>/<int:day>/',
         PostDayArchiveView.as_view(),
         name="archive_day"),
    path('today/',
         PostTodayArchiveView.as_view(),
         name="archive_today"),

    path('comment/create/<int:pk>/', CommentCreate.as_view(), name='comment_create'),
    path('comment/reply/<int:pk>/', CommentReply.as_view(), name='comment_reply'),
    path('thanks/', ThanksTemplateView.as_view(), name='thanks'),
]

yyxiaozhan/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from error import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    path('account/', include('account.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('portfolio/', include('portfolio.urls', namespace='portfolio')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# 增加的条目
handler400 = views.bad_request
handler403 = views.permission_denied
handler404 = views.page_not_found
handler500 = views.error

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.conf import settings
from django.urls import reverse
from taggit.managers import TaggableManager
from ckeditor_uploader.fields import RichTextUploadingField


# Create your models here.
# 自定义published管理器
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


# 博客模型
class Post(models.Model):
    STATUS_CHOICES = (('draft', '草稿态'), ('published', '发布态'))

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='blog_posts')
    body = RichTextUploadingField(default='请在这里输入博客正文')
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True, db_index=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    explored = models.PositiveIntegerField(db_index=True, default=0)  # 计算博客访问量
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='posts_liked', blank=True)
    total_likes = models.PositiveIntegerField(db_index=True, default=0)

    objects = models.Manager()  # 默认的管理器
    published = PublishedManager()  # 自定义管理器

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.pk])

    tags = TaggableManager()


# 评论模型
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='blog_comments')
    parent_comment = models.ForeignKey('self', on_delete=models.CASCADE, related_name='children_comments', null=True)
    body = RichTextUploadingField(default='发表您的评论')
    created = models.DateTimeField(auto_now_add=True, db_index=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ("created",)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.author, self.post)

blog/views.py
# -*- coding: utf-8 -*-
# 普通博客列表、详情基类
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
# 归档博客列表基类
from django.views.generic.dates import YearArchiveView
from django.views.generic.dates import MonthArchiveView
from django.views.generic.dates import WeekArchiveView
from django.views.generic.dates import DayArchiveView
from django.views.generic.dates import TodayArchiveView
# 博客模型引入
from .models import Post, Comment
# 引入标签选择功能
from taggit.models import Tag
from django.shortcuts import get_object_or_404
from django.db.models import Count
# 权限控制
from django.contrib.auth.mixins import LoginRequiredMixin
# 评论操作
from django.views.generic.edit import CreateView
from django.views.generic.base import TemplateView


# Create your views here.
# 博客列表类视图
class PostList(LoginRequiredMixin, ListView):
    model = Post
    template_name = "blog/post_list.html"
    context_object_name = 'all_published_posts'
    paginate_by = 4  # if pagination is desired
    ordering = '-publish'
    page_kwarg = 'page'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag'] = None
        return context

    def get_queryset(self):
        return Post.published.all()


class PostListByTag(LoginRequiredMixin, ListView):
    model = Post
    template_name = "blog/post_list.html"
    context_object_name = 'all_published_posts'
    paginate_by = 4  # if pagination is desired
    ordering = '-publish'
    page_kwarg = 'page'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag'] = self.tag
        return context

    def get_queryset(self):
        self.tag = get_object_or_404(Tag, slug=self.kwargs['tag_slug'])
        return Post.published.filter(tags__in=[self.tag])


class PostDetail(LoginRequiredMixin, DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_list'] = Comment.objects.filter(active=True, post=super().get_object())
        # 显示相近Tag的文章列表
        post_tags_ids = self.object.tags.values_list('id', flat=True)
        similar_tags = Post.published.filter(tags__in=post_tags_ids).exclude(id=self.object.id)
        context['similar_posts'] = similar_tags.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
        return context

    def get_object(self):
        obj = super().get_object()
        # 增加额外操作--每访问一次详情页，则浏览次数加1
        obj.explored += 1
        obj.save(update_fields=['explored', ])
        return obj


# 博客年归档
class PostYearArchiveView(LoginRequiredMixin, YearArchiveView):
    queryset = Post.objects.all()
    date_field = "publish"
    make_object_list = True
    allow_future = True


# 博客月归档
class PostMonthArchiveView(LoginRequiredMixin, MonthArchiveView):
    queryset = Post.objects.all()
    date_field = "publish"
    allow_future = True
    template_name = "blog/post_list.html"
    context_object_name = 'all_published_posts'
    paginate_by = 4  # if pagination is desired
    ordering = '-publish'
    page_kwarg = 'page'


# 博客周归档
class PostWeekArchiveView(LoginRequiredMixin, WeekArchiveView):
    queryset = Post.objects.all()
    date_field = "publish"
    week_format = "%W"
    allow_future = True


# 博客日归档
class PostDayArchiveView(LoginRequiredMixin, DayArchiveView):
    queryset = Post.objects.all()
    date_field = "publish"
    allow_future = True


# 博客今日归档
class PostTodayArchiveView(LoginRequiredMixin, TodayArchiveView):
    queryset = Post.objects.all()
    date_field = "publish"
    allow_future = True


# 博文回复
class CommentCreate(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ['body']
    template_name = 'blog/comment_create.html'
    success_url = '/blog/thanks/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['target'] = get_object_or_404(Post, pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        form.instance.post = self.get_context_data()['target']
        form.instance.author = self.request.user
        return super().form_valid(form)


# 评论回复
class CommentReply(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ['body']
    template_name = 'blog/comment_reply.html'
    success_url = '/blog/thanks/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['target'] = get_object_or_404(Comment, pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        form.instance.post = self.get_context_data()['target'].post
        form.instance.author = self.request.user
        form.instance.parent_comment = self.get_context_data()['target']
        return super().form_valid(form)


# 感谢页面
class ThanksTemplateView(TemplateView):

    template_name = "blog/thanks.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['info'] = "评论成功发表！"
        return context

blog/templates/blog/comment_create.html
{% extends 'base.html' %}
{% block title %}博文回复{% endblock %}
{% block content %}
    <div id="content">
        <div class="container">
            <div class="one">
                <blockquote>
                   <h4>您正在回复{{ target.author.first_name }}于{{ target.publish }}发表的博文<a href="{{ target.get_absolute_url }}">"{{ target.title }}"</a></h4>
                </blockquote>
            </div>
            <section class="one">
				<form action="." id="contact-form" class="simple-form " method="post">{% csrf_token %}
					<div id="error-field">
					</div>
					<fieldset>
						<div class="input-title">
							Your Message:
						</div>
						<textarea cols="60" rows="12" title="Your Message" class="text requiredField" name="body"></textarea>
					</fieldset>
					<div class="three-fourth">
						<input type="submit" value="Send message" class="button big grey round"/>
					</div>
				</form>
			</section>
        </div>
    </div>
{% endblock %}

blog/templates/blog/comment_reply.html
{% extends 'base.html' %}
{% block title %}评论回复{% endblock %}
{% block content %}
    <div id="content">
        <div class="container">
            <div class="one">
                <blockquote>
                    <h4>您正在回复{{ target.author.first_name }}于{{ target.created }}发表的评论，
                        该评论指向博文<a href="{{ target.post.get_absolute_url }}">"{{ target.post.title }}"</a></h4>
                </blockquote>
            </div>
            <section class="one">
                <form action="." id="contact-form" class="simple-form " method="post">{% csrf_token %}
                    <div id="error-field">
                    </div>
                    <fieldset>
                        <div class="input-title">
                            Your Message:
                        </div>
                        <textarea cols="60" rows="12" title="Your Message" class="text requiredField"
                                  name="body"></textarea>
                    </fieldset>
                    <div class="three-fourth">
                        <input type="submit" value="Send message" class="button big grey round"/>
                    </div>
                </form>
            </section>
        </div>
    </div>
{% endblock %}

blog/templates/blog/latest_posts.html
<ul class="sidebar-nav">
    {% for post in latest_posts %}
        <li><a href="{{ post.get_absolute_url }}" title="{{ post.title }}"><i
                class="icon-file-text"></i>{{ post.title }}</a></li>
    {% endfor %}
</ul>

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% block title %}博客详情{% endblock %}
{% block content %}
    <div id="content">
        <div id="breadcrumb">
            <!-- breadcrumb starts-->
            <div class="container">
                <div class="one-half">
                    <h4>博文详情</h4>
                </div>
                <div class="one-half">
                    <nav id="breadcrumbs">
                        <!--breadcrumb nav starts-->
                        <ul>
                            <li>You are here:</li>
                            <li><a href="{% url 'index' %}">Home</a></li>
                            <li>Blog Post</li>
                        </ul>
                    </nav>
                    <!--breadcrumb nav ends -->
                </div>
            </div>
        </div>
        <!--breadcrumbs ends -->
        <div class="container">
            <div class="one">
                <div class="three-fourth">
                    <div class="blog-post">
                        <div class="permalink">
                            <h4><a href="#">{{ object.title }}</a></h4>
                        </div>
                        <ul class="post-meta">
                            <li><i class="icon-time"></i>{{ post.publish|date:"Y/m/d" }}</li>
                            <!-- Date -->
                            <li><i class="icon-user"></i><a href="#">{{ post.author.first_name }}</a></li>
                            <!-- Author -->
                            <li><i class="icon-tags"></i>
                                {% for tag in post.tags.all %}
                                    <a href="{% url "blog:post_list_by_tag" tag.slug %}">{{ tag.name }}</a>
                                    {% if not forloop.last %}, {% endif %}
                                {% endfor %}
                            </li>
                            <!-- Category -->
                            <li><i class="icon-comments"></i><a href="#">{{ post.comments.count }}</a></li>
                            <!-- Comments -->
                            <li><i class="icon-eye-open"></i><a href="#">{{ post.explored }}</a></li>
                            <!-- Explored -->
                        </ul>
                        <!-- End post-meta -->
                        <div class="post-intro">
                            {{ object.body|safe }}
                            <div class="post-author">
                                <img src="images/avatars/avatar-01.png" alt=""/>
                                <div class="about-description">
                                    <h4>{{ object.author.first_name }}</h4><span class="reply"><a
                                        href="{% url 'blog:comment_create' object.pk %}"><i class="icon-reply"></i>回复本篇博文</a></span>
                                    <p><strong>相似博文</strong></p>
                                    <ul>
                                    {% for item in similar_posts %}
                                    <li>
                                        <a href="{{ item.get_absolute_url }}" >{{ item.title }} by {{ item.author.first_name }}</a>
                                    </li>
                                    {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>

                    <section class="comments-sec">
                        <ul class="commentlist">
                            {% for comment in comment_list %}
                                <li class="comment {% if comment.parent_comment %}child{% endif %}">
                                    <div class="comment">
                                        <div class="avatar">
                                            <img src="images/avatars/avatar-03.png" alt=""/>
                                        </div>
                                        <div class="comment-entry">
                                            <div class="comment-arrow">
                                            </div>
                                            <div class="comment-author">
                                                {% if comment.parent_comment %}
                                                <strong>{{ comment.author.first_name }}</strong><span class="date">{{ comment.created }}回复</span>
                                                <strong>{{ comment.parent_comment.author.first_name }}</strong><span class="date">{{ comment.parent_comment.created }}发表的评论</span>
                                                {% else %}
                                                <strong>{{ comment.author.first_name }}</strong><span class="date">{{ comment.created }}</span>
                                                {% endif %}
                                                <span
                                                    class="reply"><a href="{% url 'blog:comment_reply' comment.pk %}"><i
                                                    class="icon-reply"></i>回复本条评论</a></span>
                                            </div>
                                            <p>
                                                {{ comment.body }}
                                            </p>
                                        </div>
                                    </div>
                                </li>
                            {% empty %}
                                <li><h5>本博文尚未有人评论</h5></li>
                            {% endfor %}

                        </ul>
                    </section>
                </div>
                {% include 'blog/right-side-bar.html' %}
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}

{% block title %}博客列表{% endblock %}
{% block content %}
    <div id="content">
        <div id="breadcrumb">
            <!-- breadcrumb starts-->
            <div class="container">
                <div class="one-half">
                    <h4>
                        {% if tag %}
                            含有"{{ tag.name }}"标签的博客列表
                        {% elif month %}
                            "{{ month|date:"F Y" }}"博客归档
                        {% else %}
                            博客列表
                        {% endif %}
                    </h4>
                </div>
                <div class="one-half">
                    <nav id="breadcrumbs">
                        <!--breadcrumb nav starts-->
                        <ul>
                            <li>You are here:</li>
                            <li><a href="{% url 'index' %}">Home</a></li>
                            <li>Blog</li>
                        </ul>
                    </nav>
                    <!--breadcrumb nav ends -->
                </div>
            </div>
        </div>
        <!--breadcrumbs ends -->
        <div class="container">
            <div class="one">
                <div class="three-fourth">

                    {% for post in all_published_posts %}
                        <div class="blog-post layout-1">
                            <div class="permalink">
                                <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
                            </div>
                            <ul class="post-meta">
                                <li><i class="icon-time"></i>{{ post.publish|date:"Y/m/d" }}</li>
                                <!-- Date -->
                                <li><i class="icon-user"></i><a href="#">{{ post.author.first_name }}</a></li>
                                <!-- Author -->
                                <li><i class="icon-tags"></i>
                                    {% for tag in post.tags.all %}
                                        <a href="{% url "blog:post_list_by_tag" tag.slug %}">{{ tag.name }}</a>
                                        {% if not forloop.last %}, {% endif %}
                                    {% endfor %}
                                </li>
                                <!-- Category -->
                                <li><i class="icon-comments"></i><a href="#">{{ post.comments.count }}</a></li>
                                <!-- Comments -->
                                <li><i class="icon-eye-open"></i><a href="#">{{ post.explored }}</a></li>
                                <!-- Explored -->
                            </ul>
                            <!-- End post-meta -->
                            <div class="post-intro">
                                {{ post.body|safe|truncatechars_html:100 }}
                                <br/>
                                <p>
                                    <a href="{{ post.get_absolute_url }}" class="button simple-grey small round">查看详情</a>
                                </p>
                            </div>
                        </div>
                    {% empty %}
                        暂时还未发表任何博客
                    {% endfor %}

                    {% include 'pagination.html' with page=page_obj %}
                </div>
                {% include 'blog/right-side-bar.html' %}
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/right-side-bar.html
{% load blog_tags %}
<div class="one-fourth sidebar right">
    <div class="widget">
        <nav class="top-search">
            <!-- search starts-->
            <form action="404-error.html" method="get">
                <button class="search-btn"></button>
                <input class="search-field" type="text" onblur="if(this.value=='')this.value='Search';"
                       onfocus="if(this.value=='Search')this.value='';" value="Search"/>
            </form>
        </nav>
    </div>
    <div class="widget">
        <h4 class="widget-title">博客统计信息</h4>
        <p>
            截至{% now "Y年m月d日 h:m" %}, 已发布了{% total_posts %}篇文章
        </p>
    </div>
    <div class="widget">
        <h4 class="widget-title">最新发表博文TOP5</h4>
        {% show_latest_posts 5 %}
    </div>
    <div class="widget">
        <h4 class="widget-title">最多评论博文TOP5</h4>
        {% get_most_commented_posts as most_commented_posts %}
        <ul class="sidebar-nav">
            {% for post in most_commented_posts %}
            <li><a href="{{ post.get_absolute_url }}" title="{{ post.title }}">
                <i class="icon-file-text-alt"></i>{{ post.title }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
    <div class="widget">
        <h4 class="widget-title">博文归档</h4>
        {% get_pub_date_list as pub_date_list %}
        <ul class="sidebar-nav">
            {% for year, month in pub_date_list %}
            <li><a href="{% url 'blog:archive_month' year month %}" title="{{ year }}年{{ month }}月">
                <i class="icon-angle-right"></i>{{ year }}年{{ month }}月</a>
            </li>
            {% endfor %}
        </ul>
    </div>
    <div class="widget">
        <h4 class="widget-title">标签筛选</h4>
        {% get_all_tags as all_tags %}
        <ul class="popular-tags">
            {% for tag in all_tags %}
            <li><a href="{% url "blog:post_list_by_tag" tag.slug %}"><i class="icon-tag"></i>{{ tag.name }}</a></li>
            {% endfor %}
        </ul>
    </div>
</div>

blog/templates/blog/thanks.html
{% extends 'base.html' %}
{% block title %}感谢页{% endblock %}
{% block content %}
    <div id="content">
        <div class="container">
            <h1>{{ info }}</h1>
        </div>
    </div>
{% endblock %}