blog/urls.py
from django.urls import path
from .views import PostList, PostListByTag, PostDetail
from .views import PostYearArchiveView
from .views import PostMonthArchiveView
from .views import PostWeekArchiveView
from .views import PostDayArchiveView
from .views import PostTodayArchiveView
from .views import CommentCreate, CommentReply, ThanksTemplateView

app_name = 'blog'
urlpatterns = [
    # post CBVs
    path('list/', PostList.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>/', PostListByTag.as_view(), name='post_list_by_tag'),
    path('detail/<int:pk>/', PostDetail.as_view(), name='post_detail'),

    path('<int:year>/',
         PostYearArchiveView.as_view(),
         name="post_year_archive"),
    # Example: /2012/08/
    path('<int:year>/<int:month>/',
         PostMonthArchiveView.as_view(month_format='%m'),
         name="archive_month_numeric"),
    # Example: /2012/aug/
    path('<int:year>/<str:month>/',
         PostMonthArchiveView.as_view(),
         name="archive_month"),
    # Example: /2012/week/23/
    path('<int:year>/week/<int:week>/',
         PostWeekArchiveView.as_view(),
         name="archive_week"),
    # Example: /2012/nov/10/
    path('<int:year>/<str:month>/<int:day>/',
         PostDayArchiveView.as_view(),
         name="archive_day"),
    path('today/',
         PostTodayArchiveView.as_view(),
         name="archive_today"),

    path('comment/create/<int:pk>/', CommentCreate.as_view(), name='comment_create'),
    path('comment/reply/<int:pk>/', CommentReply.as_view(), name='comment_reply'),
    path('thanks/', ThanksTemplateView.as_view(), name='thanks'),
]

portfolio/urls.py
from django.urls import path
from .views import ImageList, ImageDetail

app_name = 'portfolio'
urlpatterns = [
    # image CBVs
    path('image/list/', ImageList.as_view(), name='image_list'),
    path('image/detail/<int:pk>/', ImageDetail.as_view(), name='image_detail'),
]

yyxiaozhan/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from error import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    path('account/', include('account.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('portfolio/', include('portfolio.urls', namespace='portfolio')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# 增加的条目
handler400 = views.bad_request
handler403 = views.permission_denied
handler404 = views.page_not_found
handler500 = views.error

templates/base.html
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}Shifter - Responsive HTML5 Template{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="shortcut icon" href="{% static 'images/favicon.gif' %}"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" media="screen"/><!-- MAIN STYLE CSS FILE -->
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}" media="screen"/><!-- RESPONSIVE CSS FILE -->
    <link rel="stylesheet" id="style-color" href="{% static 'css/colors/blue-color.css' %}" media="screen"/>
    <!-- DEFAULT BLUE COLOR CSS FILE -->
    <link href='{% static 'from_internet/css' %}' rel='stylesheet' type='text/css'>
    <!-- ROBOTO FONT FROM GOOGLE CSS FILE -->
    <link rel="stylesheet" href="{% static 'css/prettyPhoto.css' %}" media="screen"/><!--PRETTYPHOTO CSS FILE -->
    <link rel="stylesheet" href="{% static 'css/font-awesome/font-awesome.min.css' %}" media="screen"/>
    <!-- FONT AWESOME ICONS CSS FILE -->
    <link rel="stylesheet" href="{% static 'css/layer-slider.css' %}" media="screen"/><!-- LAYER SLIDER CSS FILE -->
    <link rel="stylesheet" href="{% static 'css/flexslider.css' %}" media="screen"/><!-- FLEX SLIDER CSS FILE -->
    <link rel="stylesheet" href="{% static 'css/revolution-slider.css' %}" media="screen"/>
    <!-- REVOLUTION SLIDER CSS FILE -->
    <!-- All JavaScript Files (FOR FASTER LOADING OF YOUR SITE, REMOVE ALL JS PLUGINS YOU WILL NOT USE)-->
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script><!-- JQUERY JS FILE -->
    <script type="text/javascript" src="{% static 'from_internet/js/jquery-ui.js' %}"></script>
    <!-- JQUERY UI JS FILE -->
    <script type="text/javascript" src="{% static 'js/flex-slider.min.js' %}"></script><!-- FLEX SLIDER JS FILE -->
    <script type="text/javascript" src="{% static 'js/navigation.min.js' %}"></script><!-- MAIN NAVIGATION JS FILE -->
    <script type="text/javascript" src="{% static 'js/jquery.layerslider.js' %}"></script><!-- LAYER SLIDER JS FILE -->
    <script type="text/javascript" src="{% static 'js/layerslider.transitions.js' %}"></script>
    <!-- LAYER SLIDER TRANSITIONS JS FILE -->
    <script type="text/javascript" src="{% static 'js/map.min.js' %}"></script><!-- GOOGLE MAP JS FILE -->
    <script type="text/javascript" src="{% static 'js/carousel.js' %}"></script><!-- CAROUSEL SLIDER JS -->
    <script type="text/javascript" src="{% static 'js/jquery.theme.plugins.min.js' %}"></script>
    <!-- REVOLUTION SLIDER PLUGINS JS FILE -->
    <script type="text/javascript" src="{% static 'js/jquery.themepunch.revolution.min.js' %}"></script>
    <!-- REVOLUTION SLIDER JS FILE -->
    <script type="text/javascript" src="{% static 'js/flickr.js' %}"></script><!-- FLICKR WIDGET JS FILE -->
    <script type="text/javascript" src="{% static 'js/instagram.js' %}"></script><!-- INSTAGRAM WIDGET JS FILE -->
    <script type="text/javascript" src="{% static 'js/jquery.twitter.js' %}"></script><!--TWITTER WIDGET JS FILE -->
    <script type="text/javascript" src="{% static 'js/prettyPhoto.min.js' %}"></script><!-- PRETTYPHOTO JS FILE -->
    <script type="text/javascript" src="{% static 'js/jquery.tooltips.min.js' %}"></script><!-- TOOLTIPS JS FILE -->
    <script type="text/javascript" src="{% static 'js/isotope.min.js' %}"></script><!--ISOTOPE JS FILE -->
    <script type="text/javascript" src="{% static 'js/scrolltopcontrol.js' %}"></script><!-- SCROLL TO TOP JS PLUGIN -->
    <script type="text/javascript" src="{% static 'js/jquery.easy-pie-chart.js' %}"></script><!-- EASY PIE JS FILE -->
    <script type="text/javascript" src="{% static 'js/jquery.transit.min.js' %}"></script><!-- TRANSITION JS FILE -->
    <script type="text/javascript" src="{% static 'js/custom.js' %}"></script><!-- CUSTOM JAVASCRIPT JS FILE -->
</head>
<body>
<div id="container">
    <!-- main container starts-->
    <div id="wrapp">
        <!-- main wrapp starts-->
        <header id="header">
            <!--header starts -->
            <div id="header-links">
                <div class="container">
                    <div class="one-half">
                        <ul class="contact-links">
                            <!-- header social links starts-->
                            <li><a href="#"><i class="icon-home"></i>5 Avenue, Some City </a></li>
                            <li><a href="#"><i class="icon-phone"></i>+987 654 321 </a></li>
                            <li><a href="#"><i class="icon-map-marker"></i>mail@yoursite.com</a></li>
                        </ul>
                    </div>
                    <div class="one-half">
                        <nav class="top-search">
                            <!-- search starts-->
                            <form action="." method="get">
                                <button class="search-btn"></button>
                                <input class="search-field" type="text" onblur="if(this.value=='')this.value='Search';"
                                       onfocus="if(this.value=='Search')this.value='';" value="Search"/>
                            </form>
                        </nav>
                        <!--search ends -->
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="head-wrapp">
                    <a href="{% url 'index' %}" id="logo"><img src="{% static 'images/logo.png' %}"
                                                        alt=""/><span>Responsive Business Template</span></a>
                    <!--your logo-->
                    <ul class="social-links alternative">
                        <!-- header social links starts-->
                        <li><a href="#" class="twitter tooltip" title="Some Title"><i class="icon-twitter"></i></a></li>
                        <li><a href="#" class="facebook tooltip" title="Some Title"><i class="icon-facebook"></i></a>
                        </li>
                        <li><a href="#" class="linkedin tooltip" title="Some Title"><i class="icon-linkedin"></i></a>
                        </li>
                        <li><a href="#" class="google tooltip" title="Some Title"><i class="icon-google-plus"></i></a>
                        </li>
                        <li><a href="#" class="skype tooltip" title="Some Title"><i class="icon-skype"></i></a></li>
                        <li><a href="#" class="dribbble tooltip" title="Some Title"><i class="icon-dribbble"></i></a>
                        </li>
                        <li><a href="#" class="pinterest tooltip" title="Some Title"><i class="icon-pinterest"></i></a>
                        </li>
                        <li><a href="#" class="tumblr tooltip" title="Some Title"><i class="icon-tumblr"></i></a></li>
                    </ul>
                    <!--header social links ends -->
                </div>
            </div>
            <div id="main-navigation">
                <!--main navigation wrapper starts -->
                <div class="container">
                    <ul class="main-menu">
                        <li><a href="{% url 'index' %}"
                               id="{% if request.path == "/account/index/" %}current{% endif %}"><i
                                class="icon-home"></i>Home</a>
                        </li>
                        <li><a href="#"
                               id="{% if request.path|slice:"11" == "/portfolio/" %}current{% endif %}"><i
                                class="icon-suitcase"></i> Portfolio</a>
                                <!-- Second Level / Start -->
                                <ul>
                                    <li><a href="{% url 'portfolio:image_list' %}">图片</a></li>
                                </ul>
                                <!-- Second Level / End -->
                            </li>
                        {% if request.user.is_authenticated %}
                            <li><a href="{% url 'blog:post_list' %}"
                                   id="{% if request.path|slice:"6" == "/blog/" %}current{% endif %}"><i
                                    class="icon-pencil"></i>博客</a>
                            </li>
                            <li><a href="#"
                                   id="{% if request.path|slice:"9" == "/account/" and section != 'index' %}current{% endif %}"><i
                                    class="icon-user"></i>用户管理</a>
                                 <!-- Second Level / Start -->
                                <ul>
                                    <li><a href="{% url 'password_change' %}">密码修改</a></li>
                                    <li><a href="{% url 'edit' %}">用户扩展信息编辑</a></li>
                                </ul>
                                <!-- Second Level / End -->
                            </li>
                        {% endif %}
                    </ul>
                    <!-- main navigation ends-->
                    <div class="after-nav-info alt">
                        <span class="user">
                            {% if request.user.is_authenticated %}
                                Hello {{ request.user.first_name }}
                                <a href="{% url 'logout' %}">Logout</a>
                            {% else %}
                                <a href="{% url 'login' %}">Log-in</a>
                            {% endif %}
                        </span>
                    </div>
                </div>
            </div>
            <!--main navigation wrapper ends -->
        </header>
        <!-- header ends-->
        {% block content %}{% endblock %}
        <section class="footer-call-to-action"><!-- footer call to action starts -->
            <section class="container">
                <div class="three-fourth">
                    <h4>If you you’re interested in working with Us, feel free to contact Us via contact form.</h4>
                </div>
                <div class="one-fourth">
                    <a href="#" class="button grey huge round">Purchase Now</a>
                </div>
            </section>
        </section><!-- footer call to action ends -->
        <footer id="footer" class="style-01"><!--footer starts -->
            <section class="container">
                <div class="one-fourth">
                    <!-- footer text widget starts-->
                    <p>
                        <img src="{% static 'images/logo-footer.png' %}" alt=""/>
                    </p>
                    <p>
                        Integer libero lectus, porta acean pulvinar ac, facilisis non arcu. Maecenas enim orci,
                        adipiscing dictum sit amet gusce dapibus.
                    </p>
                    <p>
                        Maecenas enim orci, adipiscing dictum sit amet gusce dapibus.
                    </p>
                    <!-- footer text widget ends-->
                </div>
                <section class="one-fourth">
                    <h4>Twitter Feeds</h4>
                    <ul class="twitter-feeds">
                        <!-- twitter widget starts-->
                    </ul>
                    <!-- twitter widget ends-->
                    <p>
                        <a href="#">Follow Me on Twitter</a>
                    </p>
                </section>
                <section class="one-fourth">
                    <h4>Latest Posts</h4>
                    <ul>
                        <!-- latest posts widget starts-->
                        <li><a href="#">Free Responsive HTML5 Template.</a></li>
                        <li><a href="#">PSD Widget UI Free Download</a></li>
                        <li><a href="#">Free Business Bootsrap Template</a></li>
                        <li><a href="#">Custom WordPress Themes</a></li>
                    </ul>
                    <!-- lastest posts widget ends-->
                </section>
                <section class="one-fourth">
                    <h4>Flickr Photos</h4>
                    <div class="flickr-widget">
                        <!-- flickr widget starts-->
                    </div>
                </section>
            </section>
        </footer>
        <section id="copyrights">
            <section class="container">
                <div class="one-half">
                    <p>
                        Copyright &copy; 2014.Company name All rights reserved.More Templates <a
                            href="http://www.cssmoban.com/" target="_blank" title="模板之家">模板之家</a> - Collect from <a
                            href="http://www.cssmoban.com/" title="网页模板" target="_blank">网页模板</a>
                    </p>
                </div>
                <div class="one-half">
                    <ul class="copyright_links">
                        <li><a href="#" title="Home">Home</a></li>
                        <li><a href="#" title="About">About us</a></li>
                        <li><a href="#" title="Blog">Blog</a></li>
                        <li><a href="#" title="Contact">Contact</a></li>
                    </ul>
                </div>
            </section>
        </section>
    </div>
    <!-- main wrapp starts-->
</div>
<!-- main container ends-->

</body>

templates/pagination.html
<!-- Pagination -->
<nav class="pagination">
    <ul>
        {% if page.has_previous %}
            <li><a href="?page={{ page.previous_page_number }}">Previous</a></li>
        {% endif %}

        {% for i in page.paginator.page_range %}
            <li><a href="?page={{ i }}" {% if page.number == i %}class="current"{% endif %}>{{ i }}</a></li>
        {% endfor %}

        {% if page.has_next %}
            <li><a href="?page={{ page.next_page_number }}">Next</a></li>
        {% endif %}
    </ul>
    <div class="clearfix">
    </div>
</nav>
<!-- End pagination -->